"""
Evidence provenance for every physical coefficient in the stack.

WHY THIS EXISTS
---------------
A simulator becomes a standard by being trusted, and trust is destroyed exactly
once: the first time someone discovers a number was invented and presented as
measured.  The incumbent, GADEN, ships MOX coefficients where four of seven
gases silently reuse methane's constants and a PID "correction factor" that is
actually an ionisation energy.  Nothing in the code or the output says so.  You
have to read the source to find out.

This module makes that impossible here.  Every coefficient carries its own
evidence level, source, and measurement conditions.  Any result can produce a
provenance report.  A run whose conclusions depend on synthesised numbers says
so, in the output, without anyone having to ask.

This turns incomplete calibration data from a liability into a differentiator:
you can ship synthesised coefficients for gases you have not yet measured,
label them precisely, and replace them incrementally as real data arrives --
with every downstream user automatically seeing which is which.

It is also the executable form of the argument in "Olfaction Standardization is
Essential for the Advancement of Embodied AI" (arXiv:2506.00398).  A standard
that specifies evidence levels is a stronger claim than one that specifies only
file formats.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import IntEnum
from typing import Any


class Evidence(IntEnum):
    """Ordered weakest to strongest. Comparisons are meaningful."""

    ASSUMED = 0
    """No external basis. A modelling choice or a placeholder. Never publish a
    quantitative claim that depends on one of these."""

    SYNTHESIZED = 1
    """Generated by a model, interpolated across gases, or transferred from a
    related analyte. Legitimate and useful -- but it is a hypothesis about the
    sensor, not a measurement of it."""

    DIGITIZED = 2
    """Read off a published figure, or algebraically inverted from third-party
    driver constants that were themselves digitised. Carries the original
    figure's reading error plus whatever the driver author's fit introduced."""

    DATASHEET = 3
    """Tabulated by the manufacturer. Typically a typical-value or a range
    across units, not a property of the specific part in your hand."""

    MEASURED = 4
    """Measured on Scentience hardware under stated conditions. Record how many
    units, over what range, at what T/RH. One unit is not a spread."""


@dataclass(frozen=True)
class Coefficient:
    """A physical constant that knows where it came from."""

    value: float
    evidence: Evidence
    source: str
    """Citation, datasheet revision, repo path, or dataset ID. Be specific
    enough that a reader can go look at the same thing you did."""

    units: str = ""
    conditions: str = ""
    """Measurement conditions: temperature, RH, concentration range, flow."""
    n_units: int = 0
    """Number of physical devices this was measured across. 0 if not measured."""
    uncertainty: float | None = None
    notes: str = ""

    def __float__(self) -> float:
        return float(self.value)

    def __repr__(self) -> str:
        u = f" +/- {self.uncertainty}" if self.uncertainty is not None else ""
        return f"{self.value}{u} [{self.evidence.name}] {self.units}".strip()


def coeff(value: float, evidence: Evidence, source: str, **kw: Any) -> Coefficient:
    return Coefficient(value=value, evidence=evidence, source=source, **kw)


# ---------------------------------------------------------------- registry ---
@dataclass
class ProvenanceRegistry:
    """Collects every coefficient a run actually touched."""

    entries: dict[str, Coefficient] = field(default_factory=dict)

    def register(self, key: str, c: Coefficient) -> Coefficient:
        self.entries[key] = c
        return c

    def weakest(self) -> Evidence:
        return min((c.evidence for c in self.entries.values()), default=Evidence.MEASURED)

    def by_level(self) -> dict[str, list[str]]:
        out: dict[str, list[str]] = {e.name: [] for e in Evidence}
        for k, c in self.entries.items():
            out[c.evidence.name].append(k)
        return {k: sorted(v) for k, v in out.items() if v}

    # ------------------------------------------------------------- reporting
    def report(self) -> str:
        lines = ["Coefficient provenance", "=" * 70]
        counts = {e.name: 0 for e in Evidence}
        for c in self.entries.values():
            counts[c.evidence.name] += 1
        total = max(len(self.entries), 1)
        for e in reversed(list(Evidence)):
            n = counts[e.name]
            if n:
                lines.append(f"  {e.name:<13} {n:>4}  ({100*n/total:5.1f}%)")
        lines.append("")
        weak = [(k, c) for k, c in sorted(self.entries.items())
                if c.evidence <= Evidence.DIGITIZED]
        if weak:
            lines.append(f"{len(weak)} coefficient(s) below DATASHEET evidence:")
            for k, c in weak:
                lines.append(f"  [{c.evidence.name:<12}] {k}")
                lines.append(f"       = {c.value!r} {c.units}   src: {c.source}")
                if c.notes:
                    lines.append(f"       note: {c.notes}")
        else:
            lines.append("All coefficients at DATASHEET evidence or above.")
        return "\n".join(lines)

    def claim_check(
        self,
        claim: str,
        required: Evidence = Evidence.MEASURED,
        depends_on: str | tuple[str, ...] | None = None,
    ) -> tuple[bool, str]:
        """
        Can this run support `claim` at `required` evidence?

        `depends_on` scopes the check to the coefficients the claim actually
        rests on -- a key prefix or tuple of prefixes, e.g. "plume." or
        ("mics6814.red.", "plume.gamma").  Omitting it checks EVERYTHING, which
        is the safe default but over-strict: a claim about plume statistics
        should not be blocked by an uncalibrated H2S sensitivity. Scope your
        claims; an unscoped check that always fails gets ignored, and an
        ignored gate is worse than no gate.

        Returns (ok, explanation); the explanation is written to be pasted into
        a limitations section verbatim.
        """
        if depends_on is None:
            scope = self.entries
        else:
            prefixes = (depends_on,) if isinstance(depends_on, str) else tuple(depends_on)
            scope = {k: c for k, c in self.entries.items() if k.startswith(prefixes)}
            if not scope:
                return False, (
                    f'"{claim}" cannot be checked: no registered coefficients match '
                    f"{prefixes!r}. Either the claim touches nothing tracked, or the "
                    "prefix is wrong -- both are bugs worth fixing before publishing."
                )
        offenders = {k: c for k, c in scope.items() if c.evidence < required}
        if not offenders:
            return True, f'"{claim}" is supported at {required.name} evidence.'
        worst = min(c.evidence for c in offenders.values())
        names = sorted(offenders)[:6]
        more = f" (+{len(offenders)-6} more)" if len(offenders) > 6 else ""
        return False, (
            f'"{claim}" CANNOT be stated at {required.name} evidence: '
            f"{len(offenders)} coefficient(s) are below it, the weakest at "
            f"{worst.name}. Offenders: {', '.join(names)}{more}. "
            f"State the claim at {worst.name} evidence instead, or measure them."
        )

    def to_json(self, path: str | None = None) -> str:
        payload = {
            k: {**asdict(c), "evidence": c.evidence.name} for k, c in sorted(self.entries.items())
        }
        s = json.dumps(payload, indent=2)
        if path:
            with open(path, "w") as f:
                f.write(s)
        return s


GLOBAL = ProvenanceRegistry()


def synthesized_from(donor_gas: str, target_gas: str, basis: str) -> str:
    """
    Canonical source string for a coefficient transferred between analytes.

    Forces the donor to be named.  GADEN's silent methane-for-everything
    substitution is invisible precisely because nothing records the donor.
    """
    return f"SYNTHESIZED: transferred from {donor_gas} to {target_gas}; basis: {basis}"
