"""The incomplete Isaac PlumeNav stub was retired; see docs/TRAINING.md.

Use the standalone environment for runnable experiments, or compose the sensor
with a completed robot task generated by Isaac Lab's current template tool.
"""
